version: '3'

services:

  centos-7:

    build: ./centos_nginx
    ports:
      - 8081:80
    volumes:
      - ./site:/opt/nginx/www.nginxtest.com
      - ./centos_nginx/logs:/opt/nginx/logs
    container_name: centos7
    networks:
      - test1
    restart: always
  

  centos-8:

    build: ./centos2_nginx
    ports:
      - 8082:80
    volumes:
      - ./site:/usr/share/nginx/html
    container_name: centos8
    networks:
      - test2
    restart: always
    
  
  ubuntu-20.04:

    build: ./ubuntu_apache2
    ports:
      - 8083:80
    volumes:
      - ./site:/opt/apache2/www.test.com
      - ./ubuntu_apache2/logs:/opt/apache2/logs
    container_name: ubuntu20.04
    networks:
      - test3
    restart: always
    

networks:
  test1:
  test2:
  test3:
