version: '3'

services:

  ubuntu-mysql:
    build: ./mysql
    image: mysql:v1
    ports:
      - 3306:3306
    container_name: mysql
    networks:
      - test1
    restart: always

  # centos7-postgresql:
  #   build: ./postgresql
  #   image: postgresql:v1
  #   ports:
  #     - 5432:5432
  #   container_name: postgresql
  #   networks:
  #     - test1
  #   restart: always

networks:
  test1:
