---
# tasks file for deploy_apache_web
- block:
    - name: install apache
      yum: name=httpd state=latest

    - name: copy index.html to servers
      copy: src=index.html dest={{ dest_file }} mode=preserve
      notify: Restart Apache

    - name: enable apache
      service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"

- block:
    - name: install apache on UBUNTU
      apt: name=apache2 state=latest

    - name: copy index.html to server
      copy: src=index.html dest={{ dest_file }} mode=preserve
      notify: Restart Apache Debian

    - name: enable apache
      service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"
