---
- name: Install Apache Web Server
  hosts: servers
  become: yes
  
  vars:
   source_file: ./site/index.html
   dest_file: /var/www/html

  tasks:

  - block:

      - name: install apache
        yum: name=httpd state=latest
  
      - name: copy index.html to servers
        copy: src={{ source_file }} dest={{ dest_file }} mode=preserve
        notify: Restart Apache

      - name: enable apache
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:

    - name: install apache on UBUNTU
      apt: name=apache2 state=latest

    - name: copy index.html to server
      copy: src={{ source_file }} dest={{ dest_file }} mode=preserve
      notify: Restart Apache Debian

    - name: enable apache
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"
  


  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
